In [1]:
import numpy as np


In [2]:
lis=[1,2,3]
np.array(lis)

array([1, 2, 3])

In [3]:
arr=array
arr

NameError: name 'array' is not defined

In [4]:
arr=np.array(lis)

In [5]:
lisoflis=[[1,4,5],[8,9],[6,5]]
np.array(lisoflis)

C:\Users\ASUS\AppData\Local\Temp/ipykernel_14952/2914333270.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(lisoflis)


array([list([1, 4, 5]), list([8, 9]), list([6, 5])], dtype=object)

In [6]:
lisoflis

[[1, 4, 5], [8, 9], [6, 5]]

In [7]:
arr

array([1, 2, 3])

In [8]:
np.array(lisoflis)

C:\Users\ASUS\AppData\Local\Temp/ipykernel_14952/1202034256.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(lisoflis)


array([list([1, 4, 5]), list([8, 9]), list([6, 5])], dtype=object)

In [9]:
np.arrange(1,10,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
s=np.arange(4,10,1)
s

array([4, 5, 6, 7, 8, 9])

In [12]:
s

array([4, 5, 6, 7, 8, 9])

In [13]:
s.sort()
s

array([4, 5, 6, 7, 8, 9])

In [14]:
s.reverse()
s

AttributeError: 'numpy.ndarray' object has no attribute 'reverse'

In [15]:
s.append(10)
s

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [16]:
s.add(8)
s

AttributeError: 'numpy.ndarray' object has no attribute 'add'

In [17]:
np.zeros(5,dtype=int)


array([0, 0, 0, 0, 0])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [20]:
s=np.linspace(0,10,10)

In [21]:
s

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
s[2]

2.2222222222222223

In [23]:
s[2]=5
s

array([ 0.        ,  1.11111111,  5.        ,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [24]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
np.random.rand(1,3)

array([[0.63828424, 0.41604757, 0.23008768]])

In [27]:
np.random.randn(2,3)

array([[ 0.64030893,  1.80542183,  1.15725328],
       [ 0.27656539, -0.64508554, -1.01789384]])

In [28]:
np.random.randint(0,10,20)

array([4, 1, 8, 3, 3, 4, 9, 8, 6, 2, 3, 9, 0, 5, 2, 7, 6, 9, 3, 5])

In [29]:
np.arange(10,38)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

In [30]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [31]:
np.arange(1,2,0.01)

array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
       1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
       1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
       1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53, 1.54,
       1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64, 1.65,
       1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76,
       1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87,
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99])